# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 713b4535235b714e084fece6f646f6f8633a99a8321a62a07b88c4282a2d052c1d6e0c8354c47b46b55da1234829d9c6cf4679d771b64ce526f46a55831e69e5

test:
  secret_key_base: 4a15ad879b62dfcc701f9555f82cc3570449727d456deb37d42e7f983ddc458d2a2e968f3cf1008bdd0ed5bef39f0c2374976eeedb2bd153c122ef4ac8bacc89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
